### ISSUE TITLE
MOBI dosyasını oluşturan betik

### ISSUE THREAD

**Issue by anezih** [bora-7/tdk-12-kindle#1]
Merhabalar,

MOBI dosyasını oluşturan programın kaynak kodunu paylaşır mısınız?

**Comment by anezih** [comment]
*"Kindle versiyonunu yaparken [bu](https://github.com/anezih/guncel-turkce-sozluk-kindle-kobo-stardict) projedeki Hunspell dosyaları tarafından yararlanılmıştır."*

Bu ifade yanlış, yararlanılmamış, bu dosya tümüyle benim yazdığım betikle oluşturulmuş, bunu düzgünce belirtebilirdiniz.

Kaldı ki otomatize edilecek bir şey de yok. kindlegen programı PATH'de olduğu sürece MOBI dosyası otomatik oluşturuluyor. En azından biçimlendirmeyle biraz oynasaymışsınız, bu kadar kör göze parmak olmazdı.

*"Ondan sonra o opf dosyasinda kindlepreviewer yazilimini kullanabilmek icin metadatayi degistirdim..."*. Baş tarafa **Ported by** veya **All rights for this port belong to Bora Akyüz** gibi ifadeler yazmak için değil yani 😃

**Comment by bora-7** [comment]
> Bu ifade yanlış, yararlanılmamış, bu dosya tümüyle benim yazdığım betikle oluşturulmuş, bunu düzgünce belirtebilirdiniz.

Yararlanılmış derken biraz resmi olarak yazmişim, bunu sizin betige yetki vermemek için boyle yazmis olmami dusunmeniz yanlis. Ama bunu simdi daha açik bir sekilde yazmak için update edecegim.

> Baş tarafa Ported by veya All rights for this port belong to Bora Akyüz gibi ifadeler yazmak için değil yani 😃

Projenin asil kismi TDK'nin 12. baskisini JSON dosyasina olusturmakti. Bu projeye basladigimda boyle bir versiyon daha internette yoktu. Bir ek olarak da kindle kullandigim icin bunun kindle port'unu yapmak istedim. Open source bir proje yaparkenki amaç baskalarinin bundan yararlanmasi degil mi? 

Dedigim gibi README'leri update edecegim. Ama hala yok kendi betigim kullanilmasin diyorsaniz su anki Kindle versiyonunu repo'dan cikartabilirim.

**Comment by bora-7** [comment]
Tamam, ben ararken bulamamistim ve [bu](https://github.com/ogun/guncel-turkce-sozluk) repo'daki en son sürüm o zaman 11. baski oldugu için kendim scrape etmeye başladim. Dediğim gibi README'leri update ettim, ama eğer kindle versiyonu durmasın diyorsanız MOBI dosyasını şimdilik (kendi converter'imi yazana kadar) sileceğim.
